name: newsfunnel_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  fluentui_system_icons: ^1.1.271
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_widget_from_html_core: ^0.15.2
  get_it: ^8.0.3
  html: ^0.15.5
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
